<?php

function mahler8_block_info()
{
    $blocks['title_banner'] = array(
        'info' => t('Title Banner'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    $blocks['social_media'] = array(
        'info' => t('Social Media'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    $blocks['people_photo'] = array(
        'info' => t('People photos'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    return $blocks;
}

function mahler8_block_view( $delta ) 
{
    $block = array();
    switch( $delta ) 
    {
        case 'title_banner':
            $block['content'] = mahler8_title_banner();
            break;
        case 'social_media':
            $block['content'] = mahler8_social_media();
            break;
        case 'people_photo':
            $block['content'] = mahler8_show_people_photo();
            break;
    }
    return $block;
}

function mahler8_title_banner()
{
    $output = '<div id="title-banner">';
    $output .= '<div class="content">';
    $output .= '<p>The Brunel Sinfonia presents<br />Mahler Symphony No. 8<br />Symphony of a Thousand</p>';
    $output .= '<p>1 Stage - 1 Symphony - 1 Night<br />508 performers<br />Sunday 24th March 2013 7.30pm<br />Colston Hall, Bristol</p>';
    $output .= '</div>';
    $output .= '<div class="tickets-link"><a target="_blank" href="http://www.colstonhall.org/whatson/Event3162" onclick="_gaq.push([\'_trackEvent\', \''.drupal_get_title().'\', \'Tickets\']);">Tickets</a></div>';
    $output .= '</div>';
    return $output;
}

function mahler8_social_media()
{
    mahler8_add_social_media_head();
    
    $output = '<div id="social_media">';
    
    $output .= mahler8_get_latest_tweet();
    
    $output .= '<div class="facebook_block">';
    $output .= '<h2>Connect with us</h2>';
    $output .= '<div class="facebook_block_like">';
    $output .= '<p>Like us on facebook</p>';
    $output .= '<div class="fb-like" data-href="http://facebook.com/brunelsinfonia" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-font="arial"></div>';
    $output .= '</div>';
    $output .= '</div>';
    
    $output .= '<div class="twitter_block">';
    $output .= '<p>Follow us on twitter</p>';
    $output .= '<div class="twitter_buttons">';
    $output .= '<a href="https://twitter.com/brunelsinfonia" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @brunelsinfonia</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';
    $output .= '<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://mahler8.com" data-text="The storm is coming" data-via="brunelsinfonia" data-hashtags="mahler8">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';
    $output .= '</div>';
    $output .= '</div>';
    
    $output .= '<div class="clear-both"></div>';    
    
    $output .= '</div>';
    
    
    
    return $output;
}

function mahler8_get_latest_tweet()
{
    $cid = 'cache:latest:tweet';
    $cached = cache_get( $cid );
    if( !$cached ) {
        $url = 'http://api.twitter.com/1/statuses/user_timeline.json?screen_name=brunelsinfonia&count=1';
        $tweets = json_decode( file_get_contents( $url ), TRUE );
        //dpm( $tweets );

        $ret = preg_replace("#(^|[\n ])([\w]+?://[\w]+[^ \"\n\r\t< ]*)#", "\\1<a href=\"\\2\" target=\"_blank\">\\2</a>", $tweets[0]['text']);
        $ret = preg_replace("#(^|[\n ])((www|ftp)\.[^ \"\t\n\r< ]*)#", "\\1<a href=\"http://\\2\" target=\"_blank\">\\2</a>", $ret);
        $ret = preg_replace("/@(\w+)/", "<a href=\"http://www.twitter.com/\\1\" target=\"_blank\">@\\1</a>", $ret);
        $ret = preg_replace("/#(\w+)/", "<a href=\"http://search.twitter.com/search?q=\\1\" target=\"_blank\">#\\1</a>", $ret);


        $output = '<div class="latest_tweet"><h2>Latest tweet</h2><p>'.$ret.'</p></div>';
        cache_set( $cid, $output, 'cache', time() + ( 60 * 60 ) );
    }
    else 
        $output = $cached->data;
    
    return $output;
}

function mahler8_add_social_media_head()
{
    
    
}

function mahler8_show_people_photo()
{
    $node = node_load( arg( 1 ) );
    $output = '';
    if( $node->type == 'people' && !empty( $node->field_photo ) ) 
    {
        $output .= theme( 'image_style', array( 'style_name' => 'people_photo', 'path' => $node->field_photo['und'][0]['uri'] ) );
    }
    return $output;
}